name: 'test-every-push'

# workflow를 동작하게 할 트리거
# 레파지토리에 push 이벤트가 발생할 때마다 실행될 것이다. +) push말고 다른 이벤트도 있음
on: 
  push:
    branches: [ main ] 

  # 작업탬에서 수동으로 테스트 가능하게 하기
  workflow_dispatch:

jobs:
  build:
    # 해당 job을 리눅스 환경에서 사용할 예정이다.
    runs-on: ubuntu-latest

    # job 안의 step 키워드는 누군가 만들어둔 action을 사용할 수 도 있고
    # shell script를 실행할 수 도 있다.
    steps:
      # github action은 해당 프로젝트를 이눅스 환경에  checkout하고 나서 실행한다.
      # 깃에 브랜치를 만들때 checkout하는 것처럼 꼭 필요함!!!!
      # 누군가 만든 Action을 사용할 때는 uses라는 키워드가 꼭 필요하다.
      - uses: actions/checkout@v2

      - name: Test_shell
        run: echo Hello, world!

      - shell: bash
        name: Secret Test
        env:
          TEST_SECRET : ${{ secrets.TELL_ME_NAME }}
          run: 

            if [ $TEST_SECRET==PEPPER ]; then echo sam; fi
          

        # with 키워드로 Action에 값을 전달할 수 있다.
        # secret에 설정한 값을 받아올 수 있는데
        # ${{ secret.XXX }} 라는 값으로 github의 Secret값을 가져올 수 있다.
